### ISSUE TITLE
Missing the FCN16.txt

### ISSUE THREAD

**Issue by John1231983** [Yuliang-Zou/tf_fcn#6]
Hello, In the train.py you used
```
f = open('./FCN16.txt', 'w')
```
But I cannot find the file in the code. I got the error as below. How can I fix it? Thanks

```
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    model = FCN16(config)
  File "/home/john/tf_fcn/src/Model.py", line 380, in __init__
    FCN32.__init__(self, config)
  File "/home/john/tf_fcn/src/Model.py", line 300, in __init__
    self.set_up()
  File "/home/john/tf_fcn/src/Model.py", line 386, in set_up
    self.add_loss_op()
  File "/home/john/tf_fcn/src/Model.py", line 355, in add_loss_op
    loss_reshape = tf.nn.sparse_softmax_cross_entropy_with_logits(pred_reshape, gt_reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1713, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1562, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by Yuliang-Zou** [comment]
`f = open('./FCN16.txt', 'w')`
This actually create a new txt file to record the training loss.

I think the error is caused by the API mismatch between old version and new version of TensorFlow. I will check it later to upgrade the code to latest version.

**Comment by John1231983** [comment]
You are right. I fixed the above error by changing 
```
loss_reshape = tf.nn.sparse_softmax_cross_entropy_with_logits(pred_reshape, gt_reshape)
```
To 
```
loss_reshape = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=pred_reshape, labels=gt_reshape)
```
Thanks
