### ISSUE TITLE
Question met when run train.py

### ISSUE THREAD

**Issue by sunbin1205** [Yuliang-Zou/tf_fcn#9]

**Comment by sunbin1205** [comment]
@Yuliang-Zou Thanks for your share! but,Question met when run train.py  

 "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by Yuliang-Zou** [comment]
Check this: #6 
That's an API inconsistency issue

**Comment by sunbin1205** [comment]
@Yuliang-Zou 
Thank you for your reply. I have solved the previous problem. But now there are new problems!
I only made one of my own data sets, building pictures. I made the error when I rerun the train and demo scripts according to the data set produced by voc2011.
For example, when you execute "train.py".
Traceback (most recent call last):
File "train. Py ", line 44, in <module>.</module>
Minibatch = data_loader. Get_next_minibatch ()
File "Dataloader. Py ", line 75, in get_next_minibatch.
Temp_result = p.m. (prep_run_wrapper, zip(temp_imName, temp_segName, temp_map, temp_size))
The File "/ home/ZBW/anaconda2 / envs/sun/lib/python2.7 / multiprocessing/pool. Py", line 253, in the map
Return self. Map_async (func, iterable, chunksize). The get ()
The File "/ home/ZBW/anaconda2 / envs/sun/lib/python2.7 / multiprocessing/pool. Py", line 572, get in
Raise the self. _value
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Can you help me see what the problem is? Or is it a concrete step to retrain the data set that needs to be modified? Thank you very much! Looking forward to your reply!!!
